import Link from "next/link";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createAdminClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";

export default async function AdminGrowthPage() {
  const db = createAdminClient() as unknown as SupabaseClient;
  const [{ count: activeOpportunities }, { count: activeMatches }, { count: companies }, { data: eventsData }] = await Promise.all([
    db.from("application_trade_opportunities").select("id", { count: "exact", head: true }).eq("is_active", true),
    db.from("lead_matches").select("id", { count: "exact", head: true }),
    db.from("companies").select("id", { count: "exact", head: true }).is("deleted_at", null),
    db.from("product_events").select("event_name").limit(10000),
  ]);
  const events = (eventsData ?? []) as Array<{ event_name: string }>;
  const signups = events.filter((event) => ["signup_completed", "account_created"].includes(event.event_name)).length;
  const unlocks = events.filter((event) => ["lead_unlocked", "opportunity_unlocked"].includes(event.event_name)).length;

  return (
    <div className="space-y-10">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-signal-orange">Growth Engine</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-charcoal">The platform should sell itself.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate">Match businesses that sell relevant services to the opportunity inventory already in the platform, then turn the strongest evidence into a reviewed teaser campaign.</p></div><Link href="/admin/prospects" className="inline-flex shrink-0 items-center justify-center rounded-xl bg-signal-orange px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#e95f00]">Review prospects →</Link></div>

      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-8"><Metric label="Qualified prospects" value="0" note="Prospect index pending" /><Metric label="Ready to contact" value="0" note="Approval queue" /><Metric label="Inventory" value={activeOpportunities ?? 0} note="active opportunities" /><Metric label="Matched signals" value={activeMatches ?? 0} note="customer matches" /><Metric label="Campaigns" value="0" note="no sends configured" /><Metric label="Signups" value={signups} note="event stream" /><Metric label="First unlocks" value={unlocks} note="tracked events" /><Metric label="Acquisition revenue" value="£0.00" note="attribution pending" /></div>

      <section className="rounded-3xl border border-light-grey bg-white p-6 sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-signal-orange">Internal loop</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-charcoal">From inventory to customer acquisition.</h2></div><span className="rounded-full bg-warning/10 px-3 py-1.5 text-xs font-semibold text-warning">Ready to connect</span></div><div className="mt-7 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><LoopCard number="01" title="Discover suppliers" body="Identify businesses whose services correspond with inferred opportunity needs." /><LoopCard number="02" title="Build Supplier Profile" body="Structure services, ideal customers, coverage, contactability and exclusions." /><LoopCard number="03" title="Match and score" body="Run the normal relevance engine and require meaningful current inventory." /><LoopCard number="04" title="Review and send" body="Generate grounded teasers, pass suppression checks and approve the campaign." /></div></section>

      <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-light-grey bg-white p-6 sm:p-8"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate">Acquisition opportunities</p><h2 className="mt-2 text-xl font-bold tracking-tight text-charcoal">Where should we concentrate?</h2></div><Link href="/admin/prospects" className="text-sm font-semibold text-signal-orange">Open queue →</Link></div><div className="mt-5 space-y-3"><OpportunityCard title="Supplier discovery index" detail="Connect Companies House, web and enrichment signals to identify businesses that can fulfil inferred needs." action="Configure discovery" /><OpportunityCard title="White-space analysis" detail="Compare opportunity supply with current customer coverage by geography and inferred need." action="Build analysis" /><OpportunityCard title="Event-triggered outreach" detail="Surface genuine inventory changes instead of timer-based follow-ups." action="Set trigger rules" /></div></section><section className="rounded-3xl border border-light-grey bg-white p-6 sm:p-8"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate">Guardrails</p><h2 className="mt-2 text-xl font-bold tracking-tight text-charcoal">Safe automation by default.</h2></div><Link href="/admin/compliance" className="text-sm font-semibold text-signal-orange">Review controls →</Link></div><ul className="mt-5 space-y-3"><Guardrail label="Minimum inventory" value="5+ relevant active opportunities" /><Guardrail label="Quality" value="At least one Hot or Warm opportunity" /><Guardrail label="Contactability" value="Verified corporate contact required" /><Guardrail label="Suppression" value="Check immediately before every send" /><Guardrail label="Automation" value="Ready to Send queue before Auto-Send" /></ul></section></div>

      <section className="rounded-3xl border border-signal-orange/20 bg-signal-orange/[0.045] p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-signal-orange">Definition of complete</p><h2 className="mt-2 text-xl font-bold tracking-tight text-charcoal">Every teaser must point to real saleable inventory.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate">The Growth Engine should never send generic “join our platform” messaging. It should be able to say how many current opportunities match the prospect, show three grounded teasers, explain the £29.99 Local starting point and £20 individual unlock, then attribute the resulting signup and revenue.</p></section>
    </div>
  );
}

function Metric({ label, value, note }: { label: string; value: string | number; note: string }) { return <div className="rounded-2xl border border-light-grey bg-white p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-charcoal">{typeof value === "number" ? new Intl.NumberFormat("en-GB").format(value) : value}</p><p className="mt-1 text-xs text-slate">{note}</p></div>; }
function LoopCard({ number, title, body }: { number: string; title: string; body: string }) { return <article className="rounded-2xl border border-light-grey bg-soft-surface p-5"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-signal-orange/10 text-xs font-bold text-signal-orange">{number}</span><h3 className="mt-4 text-sm font-semibold text-charcoal">{title}</h3><p className="mt-2 text-xs leading-5 text-slate">{body}</p></article>; }
function OpportunityCard({ title, detail, action }: { title: string; detail: string; action: string }) { return <div className="rounded-2xl border border-light-grey bg-soft-surface p-4"><div className="flex items-start justify-between gap-3"><p className="text-sm font-semibold text-charcoal">{title}</p><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.08em] text-slate">Planned</span></div><p className="mt-2 text-sm leading-6 text-slate">{detail}</p><button type="button" disabled className="mt-3 rounded-xl border border-light-grey bg-white px-3 py-2 text-xs font-semibold text-slate disabled:cursor-not-allowed">{action}</button></div>; }
function Guardrail({ label, value }: { label: string; value: string }) { return <li className="flex flex-col gap-1 rounded-2xl border border-light-grey bg-soft-surface p-4 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm font-semibold text-charcoal">{label}</span><span className="text-xs text-slate sm:text-right">{value}</span></li>; }
