import Link from "next/link";

export default function AdminCampaignsPage() {
  return (
    <div className="space-y-10">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-signal-orange">Growth Engine · Campaigns</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-charcoal">Show prospects what they could buy today.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate">Campaigns use live matched inventory, not generic audience language. Start with a reviewed Ready to Send queue; enable Auto-Send only after the scoring, provenance and suppression checks are proven.</p></div><Link href="/admin/compliance" className="text-sm font-semibold text-signal-orange">Review compliance →</Link></div>

      <section className="rounded-3xl border border-light-grey bg-white p-6 sm:p-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate">Campaign builder</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-charcoal">Create a reviewed teaser campaign.</h2></div><span className="rounded-full bg-warning/10 px-3 py-1.5 text-xs font-semibold text-warning">Sending disabled</span></div><div className="mt-7 grid gap-5 lg:grid-cols-2"><Field label="Supplier or service category" value="All qualified suppliers" /><Field label="Geography" value="Any configured coverage" /><Field label="Platform Prospect Score" value="90 or higher" /><Field label="Current inventory" value="10+ matching opportunities" /><Field label="Opportunity quality" value="At least one Hot or Warm" /><Field label="Contactability" value="Verified corporate contact" /></div><div className="mt-7 rounded-2xl border border-signal-orange/20 bg-signal-orange/[0.055] p-5"><p className="text-sm font-semibold text-charcoal">Expected campaign preview</p><p className="mt-1 text-sm leading-6 text-slate">The review step will show eligible recipients, suppression count, available inventory, selected teasers, generated copy, pricing and expected send count before anything can be approved.</p></div></section>

      <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-light-grey bg-white p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate">Message structure</p><h2 className="mt-2 text-xl font-bold tracking-tight text-charcoal">Grounded email sections</h2><ol className="mt-5 space-y-3"><Step number="01" title="Why they were contacted" body="Identify the business and inferred service profile." /><Step number="02" title="Current opportunity count" body="State the number of relevant active opportunities and coverage." /><Step number="03" title="Three teaser opportunities" body="Show type, approximate geography, score, why now and likely needs—never identity or contact detail." /><Step number="04" title="Clear commercial CTA" body="Explain Local from £29.99/month and £20 per unlocked lead." /></ol></section><section className="rounded-3xl border border-light-grey bg-white p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate">Sequences</p><h2 className="mt-2 text-xl font-bold tracking-tight text-charcoal">Event-triggered follow-ups</h2><div className="mt-5 space-y-3"><Sequence title="Email 1 · Current opportunities" body="Show the strongest current matched inventory." /><Sequence title="Follow-up · New opportunities detected" body="Send only when genuinely new matching inventory appears." /><Sequence title="Follow-up · Opportunity activity" body="Highlight meaningful additional inventory, not an artificial timer." /></div></section></div>

      <section className="rounded-3xl bg-charcoal p-6 text-white sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-signal-orange">Ready-to-send queue</p><h2 className="mt-2 text-xl font-bold tracking-tight">No messages are queued.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/60">Prospect records, canonical matches, teaser selection, Resend delivery and suppression checks must be connected before an admin can approve a campaign.</p></div><button type="button" disabled className="rounded-xl bg-white/10 px-4 py-2.5 text-sm font-semibold text-white/45">Approve & send</button></div></section>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) { return <label className="block"><span className="text-xs font-semibold uppercase tracking-[0.1em] text-slate">{label}</span><select disabled defaultValue={value} className="mt-2 w-full rounded-xl border border-light-grey bg-soft-surface px-3 py-3 text-sm font-semibold text-charcoal"><option>{value}</option></select></label>; }
function Step({ number, title, body }: { number: string; title: string; body: string }) { return <li className="flex gap-3 rounded-2xl border border-light-grey bg-soft-surface p-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-signal-orange/10 text-xs font-bold text-signal-orange">{number}</span><div><p className="text-sm font-semibold text-charcoal">{title}</p><p className="mt-1 text-xs leading-5 text-slate">{body}</p></div></li>; }
function Sequence({ title, body }: { title: string; body: string }) { return <div className="rounded-2xl border border-light-grey bg-soft-surface p-4"><p className="text-sm font-semibold text-charcoal">{title}</p><p className="mt-1 text-xs leading-5 text-slate">{body}</p></div>; }
