import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the OpenNext Cloudflare adapter/wrangler locally — never
    // committed, but present after a local build/preview/deploy.
    ".open-next/**",
    ".wrangler/**",
    "cloudflare-env.d.ts",
    // Deno Edge Functions are a separate project (own runtime, own npm:/jsr:
    // import specifiers, Deno globals) — linted/typechecked via `deno lint`/
    // `deno check`, not this Next.js-oriented config. See tsconfig.json's
    // matching exclude.
    "supabase/functions/**",
  ]),
]);

export default eslintConfig;
