import Link from "next/link";

export default function AdminProspectsPage() {
  return (
    <div className="space-y-10">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-signal-orange">Growth Engine · Prospects</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-charcoal">Potential customers with evidence.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate">A prospect is a business whose Supplier Profile matches real current opportunity inventory. This queue is intentionally separate from customer leads and requires a platform-fit score before outreach.</p></div><Link href="/admin/campaigns" className="inline-flex shrink-0 items-center justify-center rounded-xl bg-signal-orange px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#e95f00]">Build campaign →</Link></div>

      <section className="rounded-3xl border border-light-grey bg-white p-6 sm:p-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate">Prospect queue</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-charcoal">Ready to qualify</h2></div><div className="flex flex-wrap gap-2"><button type="button" disabled className="rounded-xl border border-light-grey bg-soft-surface px-3 py-2 text-xs font-semibold text-slate">All prospects</button><button type="button" disabled className="rounded-xl border border-light-grey bg-soft-surface px-3 py-2 text-xs font-semibold text-slate">Score ≥ 90</button><button type="button" disabled className="rounded-xl border border-light-grey bg-soft-surface px-3 py-2 text-xs font-semibold text-slate">5+ matches</button></div></div><div className="mt-6 rounded-3xl border border-dashed border-signal-orange/30 bg-signal-orange/[0.04] p-8 text-center sm:p-12"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-signal-orange">No prospect records connected yet</p><h3 className="mt-3 text-xl font-bold tracking-tight text-charcoal">The queue will be populated from the opportunity graph.</h3><p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-slate">Once prospect discovery is enabled, each row will include the business, inferred Supplier Profile, platform-fit score, current matching inventory, contactability, suppression state and best teaser opportunities.</p><Link href="/admin/growth" className="mt-5 inline-flex rounded-xl bg-charcoal px-4 py-2.5 text-sm font-semibold text-white">View Growth Engine rules</Link></div></section>

      <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-light-grey bg-white p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate">Qualification score</p><h2 className="mt-2 text-xl font-bold tracking-tight text-charcoal">Configurable platform fit</h2><p className="mt-2 text-sm leading-6 text-slate">Do not market to every supplier discovered. Score service match, live inventory, evidence quality, geography, recency, contactability, company suitability and suppression state.</p><div className="mt-5 space-y-3"><ScoreRow label="Service match" points="25" /><ScoreRow label="Current lead inventory" points="25" /><ScoreRow label="Opportunity quality" points="20" /><ScoreRow label="Coverage fit" points="15" /><ScoreRow label="Contactability" points="10" /><ScoreRow label="Company suitability" points="5" /></div></section><section className="rounded-3xl border border-light-grey bg-white p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate">Minimum eligibility</p><h2 className="mt-2 text-xl font-bold tracking-tight text-charcoal">Value before outreach</h2><ul className="mt-5 space-y-3"><Rule title="5+ matching opportunities" body="The platform must be able to demonstrate meaningful current inventory." /><Rule title="One Hot or Warm signal" body="At least one opportunity must have a credible buying window." /><Rule title="Verified business contact" body="Use a suitable corporate contact and retain provenance." /><Rule title="Not an existing customer" body="Do not market an account already paying for access." /><Rule title="Not suppressed" body="Suppression is checked immediately before every send." /></ul></section></div>
    </div>
  );
}

function ScoreRow({ label, points }: { label: string; points: string }) { return <div className="flex items-center justify-between gap-3 rounded-xl bg-soft-surface px-4 py-3"><span className="text-sm font-semibold text-charcoal">{label}</span><span className="text-sm font-bold text-signal-orange">{points}/100</span></div>; }
function Rule({ title, body }: { title: string; body: string }) { return <li className="rounded-2xl border border-light-grey bg-soft-surface p-4"><p className="text-sm font-semibold text-charcoal">{title}</p><p className="mt-1 text-xs leading-5 text-slate">{body}</p></li>; }
