import Link from "next/link";
import type { ReactNode } from "react";
import { createClient } from "@/lib/supabase/server";
import { INTELLIGENCE_SOURCES } from "@/lib/marketplace/catalog";
import { TerritoryCheckerWidget } from "@/components/territory-checker-widget";
import { LockedOpportunityPreview } from "@/components/locked-opportunity-preview";
import { FaqSection } from "@/components/marketing/faq";
import { PricingGrid, type PricingItem } from "@/components/marketing/pricing-grid";
import { COVERAGE_PLANS, LEAD_UNLOCK_PRICE_GBP, formatMonthlyGbp } from "@/lib/coverage/pricing";

const FALLBACK_TRADES: PricingItem[] = [
  { slug: "general-builder", name: "General Builder", description: "Extensions, conversions and whole-project builds", monthlyPricePence: 2999 },
  { slug: "groundworks", name: "Groundworks", description: "Excavation, foundations, drainage and site preparation", monthlyPricePence: 2999 },
  { slug: "roofing", name: "Roofing", description: "Re-roofing, roof extensions and roofline work", monthlyPricePence: 2999 },
  { slug: "electrical", name: "Electrical", description: "Rewiring, consumer units, EV charging and new circuits", monthlyPricePence: 2999 },
  { slug: "plumbing-heating", name: "Plumbing & Heating", description: "Boilers, heating systems, bathrooms and heat pumps", monthlyPricePence: 2999 },
];

export default async function LandingPage() {
  let tradeOptions: PricingItem[] = FALLBACK_TRADES;

  try {
    const supabase = await createClient();
    const { data: trades } = await supabase.from("trade_categories").select("slug, name, description, default_monthly_price_pence").eq("is_active", true).order("display_order");
    if (trades && trades.length > 0) tradeOptions = trades.map((trade) => ({ slug: trade.slug, name: trade.name, description: trade.description, monthlyPricePence: trade.default_monthly_price_pence }));
  } catch {
    // Keep the public proposition useful when the data service is unavailable.
  }

  return (
    <div>
      <section className="relative overflow-hidden bg-soft-surface px-6 py-12 sm:py-16 lg:px-8 lg:py-24">
        <div className="pointer-events-none absolute -right-24 top-10 h-80 w-80 rounded-full border border-signal-orange/15" />
        <div className="pointer-events-none absolute -bottom-48 left-1/3 h-[30rem] w-[30rem] rounded-full border border-charcoal/5" />
        <div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.95fr_1.05fr] lg:items-center lg:gap-16">
          <div className="max-w-2xl">
            <div className="inline-flex items-center gap-2 rounded-full border border-signal-orange/20 bg-white px-3 py-1.5 text-xs font-semibold tracking-wide text-charcoal shadow-sm"><span className="h-1.5 w-1.5 rounded-full bg-signal-orange" />One platform. One intelligence engine.</div>
            <h1 className="mt-7 text-4xl font-bold leading-[1.05] tracking-tight text-charcoal sm:text-5xl lg:text-7xl">Find businesses <span className="text-signal-orange">ready to buy.</span></h1>
            <p className="mt-6 max-w-xl text-base leading-7 text-slate sm:text-lg">Tell MyTradeBox what you sell, who you sell to and where you operate. The platform finds relevant buying signals across every enabled source, then shows you why the opportunity matters now.</p>
            <div className="mt-8 grid gap-3 sm:grid-cols-3"><HeroProof label="Why now" body="See the evidence behind the buying window." /><HeroProof label="Relevant" body="Let your profile decide what belongs in the feed." /><HeroProof label="£20 unlock" body="Pay only for the individual opportunities you want." /></div>
            <div className="mt-9 flex flex-col items-start gap-3 sm:flex-row sm:items-center"><Link href="#coverage-checker" className="inline-flex items-center justify-center gap-2 rounded-xl bg-signal-orange px-5 py-3.5 text-sm font-semibold text-white shadow-lg shadow-signal-orange/20 transition hover:bg-[#e95f00]">Preview an opportunity <ArrowUpRight /></Link><Link href="#pricing" className="inline-flex items-center justify-center gap-2 rounded-xl border border-light-grey bg-white px-5 py-3.5 text-sm font-semibold text-charcoal transition hover:border-signal-orange/40">See pricing</Link></div>
          </div>
          <MarketplacePreview />
        </div>
      </section>

      <section id="coverage-checker" className="scroll-mt-24 bg-charcoal px-6 py-16 text-white sm:py-20 lg:px-8">
        <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-start lg:gap-16">
          <div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-signal-orange">Start with your profile</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Tell us what you sell. Then choose where you operate.</h2><p className="mt-5 text-base leading-7 text-white/65">The public checker gives you a feel for the signal. Your account profile goes further: products and services, ideal customer, company-size preference, exclusions and geography all help the engine decide which opportunities are worth showing.</p><div className="mt-8 space-y-4"><FlowStep number="01" title="Describe your business" body="Products, services, ideal customers and the work you do not want." /><FlowStep number="02" title="Choose your coverage shape" body="Local, Regional or Nationwide using counties, towns, cities or radius." /><FlowStep number="03" title="Review the opportunity" body="See score, likely needs, evidence, buying window and why now before you spend." /></div></div>
          <div className="min-w-0"><TerritoryCheckerWidget trades={tradeOptions} compact /><p className="mt-4 text-center text-xs font-medium text-white/45">Preview the signal for free. A complete opportunity unlock is £20; there are no lead bundles or source add-ons.</p></div>
        </div>
        <div className="mx-auto mt-10 grid max-w-7xl gap-3 sm:grid-cols-3">{COVERAGE_PLANS.map((plan) => <div key={plan.id} className="rounded-2xl border border-white/10 bg-white/[0.06] p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-white">{plan.name}</p><p className="text-sm font-bold text-signal-orange">{formatMonthlyGbp(plan.monthlyPricePence)}/mo</p></div><p className="mt-2 text-xs leading-5 text-white/55">{plan.options.join(" · ")}</p></div>)}</div>
      </section>

      <section id="how-it-works" className="bg-white px-6 py-20 sm:py-24 lg:px-8">
        <div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-signal-orange">How the platform works</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-charcoal sm:text-4xl">From public event to actionable opportunity.</h2><p className="mt-5 text-base leading-7 text-slate sm:text-lg">The backend can resolve entities, join timelines and infer needs. The customer experience stays simple: see the reason, decide if it matters and act.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><StepCard number="01" title="Build your profile" body="Tell the engine what you sell, who you serve and where you operate." /><StepCard number="02" title="See relevant signals" body="Businesses entering a buying window appear in one unified feed." /><StepCard number="03" title="Understand why now" body="Review evidence, score, likely need, timing and recommended approach." /><StepCard number="04" title="Unlock and close the loop" body={`Unlock the full lead for ${LEAD_UNLOCK_PRICE_GBP}, push it to your CRM and record the outcome.`} /></div></div>
      </section>

      <section className="bg-soft-surface px-6 py-20 sm:py-24 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[0.85fr_1.15fr] lg:px-2"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-signal-orange">See the shape before the unlock</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-charcoal sm:text-4xl">A marketplace card should earn the next action.</h2><p className="mt-5 text-base leading-7 text-slate">Preview enough to make a useful decision. The full company profile, decision-maker enrichment and evidence view become available when you unlock the individual opportunity.</p><ul className="mt-8 space-y-4"><FeatureLine>Opportunity type, approximate geography and score</FeatureLine><FeatureLine>Why-now explanation and likely products or services needed</FeatureLine><FeatureLine>Buying-window estimate and source-backed evidence</FeatureLine><FeatureLine>Company, contact and CRM access after a successful {LEAD_UNLOCK_PRICE_GBP} unlock</FeatureLine></ul><Link href="/signup" className="mt-9 inline-flex items-center gap-2 text-sm font-semibold text-signal-orange hover:text-[#e95f00]">Create your account <ArrowUpRight /></Link></div><div className="rounded-3xl bg-charcoal p-3 shadow-2xl shadow-charcoal/10 sm:p-5"><div className="rounded-2xl bg-soft-surface p-4 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate">Illustrative opportunity card</p><p className="mt-1 text-lg font-semibold text-charcoal">Relevant before unlocked</p></div><span className="rounded-full bg-signal-orange/10 px-3 py-1.5 text-xs font-bold text-signal-orange">Evidence-led</span></div><div className="mt-5"><LockedOpportunityPreview compact title={`Unlock the full lead for ${LEAD_UNLOCK_PRICE_GBP}`} body="Identity, contact detail and the complete evidence trail are protected until you choose to unlock this opportunity." teaser={{ projectType: "Commercial fit-out", status: "Buying window detected", estimatedTradeValueLow: 12000, estimatedTradeValueHigh: 28000 }} /></div></div></div></div></section>

      <section className="bg-white px-6 py-20 sm:py-24 lg:px-8"><div className="mx-auto max-w-7xl lg:px-2"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-signal-orange">All relevant sources included</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-charcoal sm:text-4xl">Six signal layers. One customer experience.</h2></div><p className="max-w-md text-sm leading-6 text-slate">These source layers power the intelligence engine; they are not separate products. The engine matches the combined evidence to your profile.</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{INTELLIGENCE_SOURCES.map((source) => <article key={source.slug} className="rounded-2xl border border-light-grey bg-soft-surface p-5"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-charcoal">{source.name}</p><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.08em] text-success">Included</span></div><p className="mt-2 text-sm leading-6 text-slate">{source.description}</p><div className="mt-4 flex flex-wrap gap-2">{source.examples.map((example) => <span key={example} className="rounded-full border border-light-grey bg-white px-2.5 py-1 text-[11px] font-medium text-slate">{example}</span>)}</div></article>)}</div></div></section>

      <PricingGrid items={tradeOptions} compact />
      <FaqSection compact />

      <section className="bg-charcoal px-6 py-20 text-white sm:py-24 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 lg:flex-row lg:items-end lg:justify-between lg:px-2"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-signal-orange">A simpler way to buy intelligence</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Pay for the geography you need. Unlock the leads you want.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/65 sm:text-lg">No vertical add-ons, no exclusive territories and no forced bundles. Just one platform fee and £20 for each individual opportunity you choose to work.</p></div><Link href="/signup" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-signal-orange px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-[#e95f00]">Create your account <ArrowUpRight /></Link></div></section>
    </div>
  );
}

function MarketplacePreview() {
  return <div className="relative mx-auto w-full max-w-xl"><div className="pointer-events-none absolute -right-6 -top-6 hidden h-24 w-24 rounded-2xl border border-signal-orange/25 sm:block" /><div className="rounded-[2rem] bg-charcoal p-3 shadow-2xl shadow-charcoal/15 sm:p-4"><div className="rounded-3xl bg-white p-4 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate">Illustrative marketplace view</p><p className="mt-1 text-lg font-semibold text-charcoal">Your unified opportunity feed</p></div><span className="rounded-full bg-signal-orange/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.1em] text-signal-orange">Profile-led</span></div><div className="mt-5 grid grid-cols-3 gap-3"><PreviewMetric label="Score" value="93/100" tone="orange" /><PreviewMetric label="Window" value="0–30 days" tone="blue" /><PreviewMetric label="Unlock" value="£20" tone="green" /></div><div className="mt-5 space-y-3"><PreviewRow label="Why now" title="New commercial activity detected" detail="Evidence and timing attached" /><PreviewRow label="Fit" title="Likely need matches your profile" detail="Profile relevance explained" /><PreviewRow label="Next" title="Make the first move" detail="Unlock, contact and track outcome" /></div><div className="mt-5 flex items-center justify-between border-t border-light-grey pt-4 text-xs"><span className="text-slate">Profile + coverage → relevance</span><span className="font-semibold text-signal-orange">Explore →</span></div></div></div><p className="mt-4 text-center text-xs font-medium text-slate">A clearer way to decide which opportunities deserve your time.</p></div>;
}

function PreviewMetric({ label, value, tone }: { label: string; value: string; tone: "orange" | "blue" | "green" }) { const styles = { orange: "border-signal-orange/25 bg-signal-orange/[0.06]", blue: "border-slate/15 bg-slate/[0.035]", green: "border-success/20 bg-success/[0.04]" }[tone]; return <div className={`rounded-2xl border p-3 ${styles}`}><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-slate">{label}</p><p className="mt-2 text-sm font-bold text-charcoal">{value}</p></div>; }
function PreviewRow({ label, title, detail }: { label: string; title: string; detail: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-light-grey bg-soft-surface p-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-signal-orange/10 text-signal-orange"><span className="h-2 w-2 rounded-full bg-signal-orange" /></span><div className="min-w-0 flex-1"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-slate">{label}</p><p className="mt-0.5 truncate text-sm font-semibold text-charcoal">{title}</p><p className="mt-0.5 text-xs text-slate">{detail}</p></div><span className="text-signal-orange">→</span></div>; }
function HeroProof({ label, body }: { label: string; body: string }) { return <div className="rounded-2xl border border-light-grey bg-white p-3 shadow-sm"><p className="text-xs font-bold text-charcoal">{label}</p><p className="mt-1 text-[11px] leading-5 text-slate">{body}</p></div>; }
function FlowStep({ number, title, body }: { number: string; title: string; body: string }) { return <div className="flex gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-white text-xs font-bold text-signal-orange">{number}</span><div><p className="text-sm font-semibold text-white">{title}</p><p className="mt-1 text-xs leading-5 text-white/55">{body}</p></div></div>; }
function StepCard({ number, title, body }: { number: string; title: string; body: string }) { return <article className="rounded-3xl border border-light-grey bg-soft-surface p-6"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-signal-orange/10 text-sm font-bold text-signal-orange">{number}</div><h3 className="mt-6 text-xl font-semibold tracking-tight text-charcoal">{title}</h3><p className="mt-3 text-sm leading-6 text-slate">{body}</p></article>; }
function FeatureLine({ children }: { children: ReactNode }) { return <li className="flex items-start gap-3 text-sm leading-6 text-charcoal"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-success/10 text-success"><CheckIcon /></span><span>{children}</span></li>; }
function CheckIcon() { return <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2.2" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="m5 12 4.5 4.5L19 7" /></svg>; }
function ArrowUpRight({ className = "h-4 w-4" }: { className?: string }) { return <svg viewBox="0 0 24 24" className={className} fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="M7 17 17 7M8 7h9v9" /></svg>; }
