import { NextResponse } from "next/server";
import { z } from "zod";
import type { SupabaseClient } from "@supabase/supabase-js";
import { requireCurrentCompany } from "@/lib/auth/get-current-company";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { getPostalOpportunityContext } from "@/lib/outreach/postal-context";
import { createOrReuseDeliveryQuoteLink } from "@/lib/outreach/response-links";
import { renderSimplePdf } from "@/lib/export/simple-pdf";

const bodySchema = z.object({
  content: z.string().trim().min(20).max(12000),
});

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const company = await requireCurrentCompany();
  const { id } = await params;
  const body = bodySchema.safeParse(await request.json().catch(() => null));
  if (!body.success) return NextResponse.json({ error: "invalid_request" }, { status: 400 });
  if (!process.env.QUOTE_LINK_SIGNING_SECRET?.trim()) {
    return NextResponse.json({ error: "quote_link_signing_secret_not_configured" }, { status: 503 });
  }

  const supabase = await createClient();
  const admin = createAdminClient() as unknown as SupabaseClient;
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "unauthenticated" }, { status: 401 });

  const context = await getPostalOpportunityContext(id);
  if (!context) return NextResponse.json({ error: "not_found" }, { status: 404 });
  if (!context.recipient) return NextResponse.json({ error: "postal_address_unavailable" }, { status: 422 });

  const { data: leadMatch } = await supabase
    .from("lead_matches")
    .select("id")
    .eq("company_id", company.id)
    .eq("application_trade_opportunity_id", id)
    .maybeSingle();

  const deliveryId = crypto.randomUUID();
  const recipient = context.recipient;
  const baseUrl = new URL(request.url).origin;

  const { error: insertError } = await admin.from("outreach_deliveries").insert({
    id: deliveryId,
    company_id: company.id,
    opportunity_id: id,
    lead_match_id: leadMatch?.id ?? null,
    channel: "letter",
    provider: "manual_pdf",
    status: "draft",
    recipient_name: recipient.name ?? context.strategy.suggestedRecipient,
    recipient_address: recipient,
    content_snapshot: body.data.content,
    audience_type: "homeowner",
    strategy_key: "planning-homeowner-introduction",
    template_key: "mytradebox-quote-link-letter",
    template_version: "1",
    created_by: user.id,
  });
  if (insertError) return NextResponse.json({ error: "delivery_create_failed" }, { status: 500 });

  try {
    const quoteLink = await createOrReuseDeliveryQuoteLink({
      companyId: company.id,
      opportunityId: id,
      deliveryId,
      channel: "letter",
      audienceType: "homeowner",
      createdBy: user.id,
      baseUrl,
    });
    const finalContent = appendQuoteLink(body.data.content, quoteLink.url);

    await admin
      .from("outreach_deliveries")
      .update({ content_snapshot: finalContent, updated_at: new Date().toISOString() })
      .eq("id", deliveryId)
      .eq("company_id", company.id);

    const recipientLines = [
      recipient.name ?? context.strategy.suggestedRecipient,
      recipient.addressLine1,
      recipient.addressLine2,
      recipient.city,
      recipient.county,
      recipient.postcode,
    ].filter((value): value is string => Boolean(value?.trim()));

    const pdf = renderSimplePdf({
      title: company.trading_name,
      subtitle: `Prepared with MyTradeBox · ${new Date().toLocaleDateString("en-GB")}`,
      sections: [
        { heading: "To", lines: recipientLines },
        { heading: "", lines: finalContent.split(/\r?\n/) },
      ],
      footer: "Private project response link included · generated by MyTradeBox",
    });
    const pdfBody = new Uint8Array(pdf).buffer;
    const district = String(context.application.postcode ?? "letter").replace(/\s+/g, "-").replace(/[^a-z0-9-]/gi, "");

    await admin.from("opportunity_activity_events").insert({
      company_id: company.id,
      opportunity_id: id,
      lead_match_id: leadMatch?.id ?? null,
      event_type: "letter_prepared",
      channel: "letter",
      provider: "manual_pdf",
      metadata: {
        delivery_id: deliveryId,
        response_link_id: quoteLink.id,
        response_url: quoteLink.url,
        audience_type: "homeowner",
      },
      created_by: user.id,
    });

    return new NextResponse(pdfBody, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="mytradebox-letter-${district}-${id.slice(0, 8)}.pdf"`,
        "Cache-Control": "private, no-store",
        "X-MyTradeBox-Delivery-Id": deliveryId,
      },
    });
  } catch (error) {
    console.error("Postal PDF generation failed", error);
    await admin
      .from("outreach_deliveries")
      .update({ status: "failed", failed_at: new Date().toISOString(), error_message: "PDF generation failed", updated_at: new Date().toISOString() })
      .eq("id", deliveryId)
      .eq("company_id", company.id);
    return NextResponse.json({ error: "postal_pdf_failed" }, { status: 502 });
  }
}

function appendQuoteLink(content: string, url: string) {
  if (content.includes(url)) return content;
  return `${content.trim()}\n\nWant to discuss the project or request a quote?\n${url}\n\nUse this private MyTradeBox response link to call, WhatsApp or request a quote directly.`;
}
