-- Seed data: the 13 initial trade categories from the product spec (more can
-- be added later with a plain INSERT, no code change needed), and a starter
-- set of real UK postcode districts so territories/reserve_territory have
-- something to reference. This is a representative sample, not the full ONS
-- dataset (~3,000 districts) — see README "Database setup" for how to import
-- the complete set later.

insert into public.trade_categories (slug, name, description, default_monthly_price_pence, display_order, ai_detection_hints) values
  ('general-builder', 'General Builder', 'Extensions, conversions, and whole-project builds', 9900, 1, '{"keywords": ["extension", "renovation", "conversion", "new dwelling", "alteration"]}'),
  ('groundworks', 'Groundworks', 'Excavation, foundations, drainage, and site preparation', 7900, 2, '{"keywords": ["foundations", "excavation", "drainage", "groundworks", "site clearance", "slab"]}'),
  ('roofing', 'Roofing', 'Re-roofing, roof extensions, and roofline work', 7900, 3, '{"keywords": ["roof", "re-roofing", "dormer", "loft", "roofline", "guttering"]}'),
  ('structural-steel', 'Structural Steel', 'Steel beams and structural alterations', 6900, 4, '{"keywords": ["steel beam", "rsj", "structural opening", "load-bearing"]}'),
  ('windows-doors', 'Windows & Doors', 'Replacement and new windows/doors, bifolds, glazing', 6900, 5, '{"keywords": ["windows", "doors", "bifold", "glazing", "fenestration"]}'),
  ('landscaping', 'Landscaping', 'Gardens, patios, boundary treatments, external works', 5900, 6, '{"keywords": ["landscaping", "garden", "patio", "boundary", "external works"]}'),
  ('electrical', 'Electrical', 'Rewiring, consumer units, EV charging, new circuits', 7900, 7, '{"keywords": ["electrical", "rewire", "consumer unit", "ev charger", "lighting"]}'),
  ('plumbing-heating', 'Plumbing & Heating', 'Boilers, heating systems, bathrooms, heat pumps', 7900, 8, '{"keywords": ["plumbing", "heating", "boiler", "bathroom", "heat pump", "central heating"]}'),
  ('brickwork', 'Brickwork', 'Blockwork, brickwork, and masonry', 6900, 9, '{"keywords": ["brickwork", "blockwork", "masonry", "repointing"]}'),
  ('demolition', 'Demolition', 'Full or partial demolition and strip-out', 5900, 10, '{"keywords": ["demolition", "strip-out", "clearance", "removal of existing"]}'),
  ('loft-conversion', 'Loft Conversion', 'Loft conversions and roof space development', 6900, 11, '{"keywords": ["loft conversion", "roof space", "dormer conversion", "hip-to-gable"]}'),
  ('driveways', 'Driveways', 'Driveways, hardstanding, and parking areas', 5900, 12, '{"keywords": ["driveway", "hardstanding", "parking area", "resin", "block paving"]}'),
  ('renewables', 'Renewables', 'Solar PV, heat pumps, and other renewable installations', 6900, 13, '{"keywords": ["solar panel", "photovoltaic", "heat pump", "renewable", "battery storage"]}');

insert into public.postcode_districts (id, postcode_area, post_town, region, country, centroid) values
  ('NR1', 'NR', 'Norwich', 'East of England', 'England', st_geogfromtext('POINT(1.2974 52.6280)')),
  ('NR2', 'NR', 'Norwich', 'East of England', 'England', st_geogfromtext('POINT(1.2800 52.6270)')),
  ('NR3', 'NR', 'Norwich', 'East of England', 'England', null),
  ('NR4', 'NR', 'Norwich', 'East of England', 'England', null),
  ('NR14', 'NR', 'Norwich', 'East of England', 'England', null),
  ('NR15', 'NR', 'Norwich', 'East of England', 'England', st_geogfromtext('POINT(1.3800 52.5100)')),
  ('NR16', 'NR', 'Norwich', 'East of England', 'England', null),
  ('IP1', 'IP', 'Ipswich', 'East of England', 'England', st_geogfromtext('POINT(1.1560 52.0590)')),
  ('IP4', 'IP', 'Ipswich', 'East of England', 'England', null),
  ('IP22', 'IP', 'Diss', 'East of England', 'England', st_geogfromtext('POINT(1.1080 52.3790)')),
  ('IP24', 'IP', 'Thetford', 'East of England', 'England', st_geogfromtext('POINT(0.7480 52.4140)')),
  ('IP32', 'IP', 'Bury St Edmunds', 'East of England', 'England', null),
  ('CB1', 'CB', 'Cambridge', 'East of England', 'England', null),
  ('CB4', 'CB', 'Cambridge', 'East of England', 'England', null),
  ('CO1', 'CO', 'Colchester', 'East of England', 'England', null),
  ('CO10', 'CO', 'Sudbury', 'East of England', 'England', null),
  ('E1', 'E', 'London', 'London', 'England', st_geogfromtext('POINT(-0.0648 51.5150)')),
  ('N1', 'N', 'London', 'London', 'England', null),
  ('SW11', 'SW', 'London', 'London', 'England', st_geogfromtext('POINT(-0.1670 51.4650)')),
  ('SE15', 'SE', 'London', 'London', 'England', null),
  ('W4', 'W', 'London', 'London', 'England', null),
  ('EN5', 'EN', 'Barnet', 'London', 'England', null),
  ('RM1', 'RM', 'Romford', 'London', 'England', null),
  ('BR1', 'BR', 'Bromley', 'London', 'England', null),
  ('B1', 'B', 'Birmingham', 'West Midlands', 'England', st_geogfromtext('POINT(-1.9026 52.4862)')),
  ('B29', 'B', 'Birmingham', 'West Midlands', 'England', null),
  ('CV1', 'CV', 'Coventry', 'West Midlands', 'England', null),
  ('WS1', 'WS', 'Walsall', 'West Midlands', 'England', null),
  ('M1', 'M', 'Manchester', 'North West England', 'England', st_geogfromtext('POINT(-2.2426 53.4808)')),
  ('M20', 'M', 'Manchester', 'North West England', 'England', null),
  ('L1', 'L', 'Liverpool', 'North West England', 'England', st_geogfromtext('POINT(-2.9916 53.4084)')),
  ('PR1', 'PR', 'Preston', 'North West England', 'England', null),
  ('LS1', 'LS', 'Leeds', 'Yorkshire and the Humber', 'England', st_geogfromtext('POINT(-1.5491 53.7997)')),
  ('LS10', 'LS', 'Leeds', 'Yorkshire and the Humber', 'England', null),
  ('S1', 'S', 'Sheffield', 'Yorkshire and the Humber', 'England', null),
  ('HU1', 'HU', 'Hull', 'Yorkshire and the Humber', 'England', null),
  ('NE1', 'NE', 'Newcastle upon Tyne', 'North East England', 'England', null),
  ('BS1', 'BS', 'Bristol', 'South West England', 'England', st_geogfromtext('POINT(-2.5879 51.4545)')),
  ('BS15', 'BS', 'Bristol', 'South West England', 'England', null),
  ('EX1', 'EX', 'Exeter', 'South West England', 'England', null),
  ('PL1', 'PL', 'Plymouth', 'South West England', 'England', null),
  ('BA1', 'BA', 'Bath', 'South West England', 'England', null),
  ('OX1', 'OX', 'Oxford', 'South East England', 'England', null),
  ('RG1', 'RG', 'Reading', 'South East England', 'England', null),
  ('GU1', 'GU', 'Guildford', 'South East England', 'England', null),
  ('BN1', 'BN', 'Brighton', 'South East England', 'England', null),
  ('ME1', 'ME', 'Rochester', 'South East England', 'England', null),
  ('CT1', 'CT', 'Canterbury', 'South East England', 'England', null),
  ('SO14', 'SO', 'Southampton', 'South East England', 'England', null),
  ('PO1', 'PO', 'Portsmouth', 'South East England', 'England', null),
  ('LE1', 'LE', 'Leicester', 'East Midlands', 'England', null),
  ('NG1', 'NG', 'Nottingham', 'East Midlands', 'England', null),
  ('DE1', 'DE', 'Derby', 'East Midlands', 'England', null),
  ('NN1', 'NN', 'Northampton', 'East Midlands', 'England', null),
  ('EH1', 'EH', 'Edinburgh', 'Scotland', 'Scotland', st_geogfromtext('POINT(-3.1883 55.9533)')),
  ('G1', 'G', 'Glasgow', 'Scotland', 'Scotland', st_geogfromtext('POINT(-4.2518 55.8642)')),
  ('CF10', 'CF', 'Cardiff', 'Wales', 'Wales', st_geogfromtext('POINT(-3.1791 51.4816)')),
  ('SA1', 'SA', 'Swansea', 'Wales', 'Wales', null),
  ('BT1', 'BT', 'Belfast', 'Northern Ireland', 'Northern Ireland', st_geogfromtext('POINT(-5.9301 54.5973)'));
